### ISSUE TITLE
Linting github job

### ISSUE THREAD

**Issue by YacineSteeve** [YacineSteeve/quizoot#17]
`pycodestyle` checks are failing, I don't know where the problem could be. Can you take a look at it ?

**Comment by chrichri17** [comment]
> `pycodestyle` checks are failing, I don't know where the problem could be. Can you take a look at it ?

I missed that. The problem is simply that you made a mess 😂

**Comment by YacineSteeve** [comment]
Me ? Nooo, I don't see what you're talking about 😂
