### ISSUE TITLE
Define the `Question` interface

### ISSUE THREAD

**Issue by chrichri17** [YacineSteeve/quizoot#19]
Requirements
--------------
- Define the`Question` object in `schemas/interface.ts` and the required sub interfaces.
- Make sure to write proper comments (used as annotations) using valid json tags:
   ```typescript
    interface Question {
        /**
         * Id of the question
         * 
         * @pattern [a-z0-9]{12}
         */
         id: string;
    }
    ```
    You can use others tags like `@minimum`, `@maxItems`, etc. See [Tjs annotations](https://github.com/YousefED/typescript-json-schema#annotations)
- Generates the json schema using [typescript-json-schema](https://www.npmjs.com/package/typescript-json-schema)
  - We should also create a new target in the `Makefile` that does it automatically.. or write a script to do so. But this is another issue
  - Right now, we can do it manually with this command : 
    ```bash
    $ tjs interface.ts Question --out question.json --noExtraProps
    ```
    Where `tjs` is an alias for `typescript-json-schema`.

What is a nice to have ?
------------------------
- Define the schemas in a modular way.

**Comment by YacineSteeve** [comment]
`Makefile` target for generating the json schema already added in local 😉 Comming in next PR
