### ISSUE TITLE
Implement a CRUD in the backend to manage `Question` and `Quiz` objects

### ISSUE THREAD

**Issue by chrichri17** [YacineSteeve/quizoot#20]
## Goals

- [x] Expose a CRUD interface to manage `Question` and `Quiz` objects
- [x] Make sure to implement it in a modular way

**Comment by YacineSteeve** [comment]
Can I make it for the front instead ?
Or even both front and back

**Comment by chrichri17** [comment]
I don't understand your question

**Comment by YacineSteeve** [comment]
Should I build the crud app at the frontend level or the backend ?

**Comment by chrichri17** [comment]
The task is probably mis explained..

I meant, expose api routes in the backend to manage Quiz and question objects.. like a classic CRUD api using django

We cannot do that in the frontend right ?

**Comment by YacineSteeve** [comment]
Okay, got it

**Comment by chrichri17** [comment]
I believe some operations are missing: `GET` question, `CREATE` question, etc...

**Comment by YacineSteeve** [comment]
Of course. It closed automatically.
But as we said, we are switching to the front now, isn't it ?

**Comment by YacineSteeve** [comment]
Remaining for `Questions`
