### ISSUE TITLE
Frontend: design the view for a single quiz

### ISSUE THREAD

**Issue by chrichri17** [YacineSteeve/quizoot#23]
Recalling that a quiz is a set of questions, design and implement the view of a quiz.

It might have a main container in the center, with an arrow to switch from the current question to the next or the previous one.

## Things to keep in mind (to improve the interface later)
- Do we want to forbid users to go back to the previous question ?

__Priority__: MEDIUM

**Comment by YacineSteeve** [comment]
I think we should let them go back. I don't see any reason to not.

**Comment by YacineSteeve** [comment]
@chrichri17 this one couldn't be closed ?

**Comment by chrichri17** [comment]
@YacineSteeve nope. I believe it's still open. We can close it after closing the children... I mean #32 and the others...
