### ISSUE TITLE
Rollback `Quizz.questions` design

### ISSUE THREAD

**Issue by chrichri17** [YacineSteeve/quizoot#57]
As discussed, we might want to rollback the design of `Quizz.questions`:

```typescript
interface Quiz {
    questions: Array<{
        question_id: string;
        next_question_id: string;
        prev_question_id: string;
    }>
}
```

Or something similar.

## Tasks
- [ ] change the interface
- [ ] update frontend (we might want to use routes like `http://localhost:PORT/api/1?questionId=123456789012345678901234`

> __PRIORITY__: HIGH

**Comment by chrichri17** [comment]
@YacineSteeve is that something interesting to you?

**Comment by YacineSteeve** [comment]
Not so much, you can do it.
