### ISSUE TITLE
Create a `data` dir

### ISSUE THREAD

**Issue by YacineSteeve** [YacineSteeve/quizoot#58]
- [ ] create a data dir with dummy quizzes and questions.

Must be a top level dir ?
<br/>
>
> __PRIORITY__ : MEDIUM
>

**Comment by chrichri17** [comment]
This is a duplicate of issue #22. I mean it's included in #22

**Comment by YacineSteeve** [comment]
You're right. But I prefer a fresh issue instead of reopening #22
