### ISSUE TITLE
[Frontend] Implement a basic `useFetch` hook

### ISSUE THREAD

**Issue by chrichri17** [YacineSteeve/quizoot#61]
## Goal

Implement a basic `useFetch` hook in the library. It can then be imported to make GET request from the frontend. We only need GET request right now (to fetch quizzes and questions)

## Possible usage

```typescript
import { useFetch } from "@/lib/hooks";
import { onBeforeMount, ref } from 'vue';
import type { Ref } from 'vue';
import type { Quizzot } from "@interfaces/quizoot";

const quizzes = ref<Quizoot.Quiz[] | null>(null);

onBeforeMount(async () => {
  const { data, error, isFetching } = await useFetch<Quizoot.Quiz[]>(`/api/quizzes`);
  quizzes.value = data;
  // Do something else
});
```

## Requirements
- [ ] return at least `data`, `error` and `isFetching` (or `isLoading`)
- [ ] should be implemented in `src/lib/hooks.ts`
- [ ] should use axios and probably the `makeRequest()` function from `@/lib/requests`

## References
- [Vue composable](https://vuejs.org/guide/reusability/composables.html#async-state-example)
- [Basic `useFetch` hook example](https://javascript.plainenglish.io/create-a-basic-usefetch-hook-in-vue-b3ff113872d7)

**Comment by chrichri17** [comment]
@YacineSteeve interested ?

**Comment by chrichri17** [comment]
As an alternative, we can just use [VueUse: usefetch](https://vueuse.org/core/usefetch/). But I thought it might be a good coding exercise.. So whatever you think might suits well.

**Comment by YacineSteeve** [comment]
Sounds interesting, I take this one
