### ISSUE TITLE
Data insertion UI

### ISSUE THREAD

**Issue by YacineSteeve** [YacineSteeve/quizoot#80]
Build a UI to easily create and modify quizzes and questions.
Something like [Vue JSON Schema Forms](https://roma219.github.io/vue-jsonschema-form/guide/#introduction).

**Comment by YacineSteeve** [comment]
> [Vue JSON Schema Forms](https://roma219.github.io/vue-jsonschema-form/guide/#introduction).

Seems only compatible with `Vue2`.
I am thinking of [JSON Forms](https://jsonforms.io/docs) as an alternative.

**Comment by chrichri17** [comment]
@YacineSteeve I'll add more directives to this issue. We should probably keep it very simple and maybe build the interface from an existing framework. Something that already does what we want.

As I said, the ideal would be to use django admin. But our JsonSchema is a slightly complex. We need to figure out a way to tell django to choose the right schema for the right resource dynamically. Let me dig a bit and come up with a much simpler solution.

Or maybe you want to come up with a proposal that we can discuss before jumping into the implementation ?
